create table groups
(id integer not null,
name text not null,
primary key(id));

create table event_type
(id integer not null,
 name text not null,
 name_en text not null,
 order_id integer not null,
 existence integer not null,
 full_name text not null,
 description text not null,
 early_round_type text not null,
 later_round_type text not null,
 primary key(id));

create table court_type
(id integer not null,
 name text not null,
 primary key(id));

create table players
(
id integer not null,
group_id integer not null,
name text not null,
name_kana text not null,
mvp integer,
junior_high_zissen_man_player_id integer unique,
junior_high_zissen_man_rank_group integer,
junior_high_zissen_man_rank_lastyear integer,
junior_high_zissen_man_rank_total integer,
junior_high_zissen_man_comment text,
higher_grades_zissen_man_player_id integer unique,
higher_grades_zissen_man_rank_group integer,
higher_grades_zissen_man_rank_lastyear integer,
higher_grades_zissen_man_rank_total integer,
higher_grades_zissen_man_comment text,
junior_high_zissen_woman_player_id integer unique,
junior_high_zissen_woman_rank_group integer,
junior_high_zissen_woman_rank_lastyear integer,
junior_high_zissen_woman_rank_total integer,
junior_high_zissen_woman_comment text,
higher_grades_zissen_woman_player_id integer unique,
higher_grades_zissen_woman_rank_group integer,
higher_grades_zissen_woman_rank_lastyear integer,
higher_grades_zissen_woman_rank_total integer,
higher_grades_zissen_woman_comment text,
junior_high_hokei_man_player_id integer unique,
junior_high_hokei_man_rank_group integer,
junior_high_hokei_man_rank_lastyear integer,
junior_high_hokei_man_rank_total integer,
junior_high_hokei_man_comment text,
higher_grades_hokei_man_player_id integer unique,
higher_grades_hokei_man_rank_group integer,
higher_grades_hokei_man_rank_lastyear integer,
higher_grades_hokei_man_rank_total integer,
higher_grades_hokei_man_comment text,
lower_grades_hokei_man_player_id integer unique,
lower_grades_hokei_man_rank_group integer,
lower_grades_hokei_man_rank_lastyear integer,
lower_grades_hokei_man_rank_total integer,
lower_grades_hokei_man_comment text,
junior_high_hokei_woman_player_id integer unique,
junior_high_hokei_woman_rank_group integer,
junior_high_hokei_woman_rank_lastyear integer,
junior_high_hokei_woman_rank_total integer,
junior_high_hokei_woman_comment text,
higher_grades_hokei_woman_player_id integer unique,
higher_grades_hokei_woman_rank_group integer,
higher_grades_hokei_woman_rank_lastyear integer,
higher_grades_hokei_woman_rank_total integer,
higher_grades_hokei_woman_comment text,
lower_grades_hokei_woman_player_id integer unique,
lower_grades_hokei_woman_rank_group integer,
lower_grades_hokei_woman_rank_lastyear integer,
lower_grades_hokei_woman_rank_total integer,
lower_grades_hokei_woman_comment text,
zissen_man_player_id integer unique,
zissen_man_rank_group integer,
zissen_man_rank_lastyear integer,
zissen_man_rank_total integer,
zissen_man_comment text,
hokei_man_player_id integer unique,
hokei_man_rank_group integer,
hokei_man_rank_lastyear integer,
hokei_man_rank_total integer,
hokei_man_comment text,
zissen_woman_player_id integer unique,
zissen_woman_rank_group integer,
zissen_woman_rank_lastyear integer,
zissen_woman_rank_total integer,
zissen_woman_comment text,
hokei_woman_player_id integer unique,
hokei_woman_rank_group integer,
hokei_woman_rank_lastyear integer,
hokei_woman_rank_total integer,
hokei_woman_comment text,
hokei_kyuui_player_id integer unique,
hokei_kyuui_rank_group integer,
hokei_kyuui_rank_lastyear integer,
hokei_kyuui_rank_total integer,
hokei_kyuui_comment text,
primary key(id),
foreign key (group_id) references groups(id));

create table notification_request
(id serial not null,
 event_id integer not null,
 player_id integer unique,
 group_id integer,
 group_name text,
 court_id integer not null,
 primary key(id),
 foreign key (event_id) references event_type(id),
 foreign key (player_id) references players(id),
 foreign key (court_id) references court_type(id));

\copy groups from 'groups.csv' csv header;
\copy event_type from 'event_type.csv' csv header;
\copy court_type from 'court_type.csv' csv header;
\copy players from 'players.csv' csv header;
